// Code generated by MockGen. DO NOT EDIT.
// Source: internal/requester/requester.go
//
// Generated by this command:
//
//	mockgen -source=internal/requester/requester.go -destination=test/mocks/mock_requester/mock_requester.go -package=mock_requester
//

// Package mock_requester is a generated GoMock package.
package mock_requester

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRequester is a mock of Requester interface.
type MockRequester[Request any, Response any] struct {
	ctrl     *gomock.Controller
	recorder *MockRequesterMockRecorder[Request, Response]
	isgomock struct{}
}

// MockRequesterMockRecorder is the mock recorder for MockRequester.
type MockRequesterMockRecorder[Request any, Response any] struct {
	mock *MockRequester[Request, Response]
}

// NewMockRequester creates a new mock instance.
func NewMockRequester[Request any, Response any](ctrl *gomock.Controller) *MockRequester[Request, Response] {
	mock := &MockRequester[Request, Response]{ctrl: ctrl}
	mock.recorder = &MockRequesterMockRecorder[Request, Response]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequester[Request, Response]) EXPECT() *MockRequesterMockRecorder[Request, Response] {
	return m.recorder
}

// Delete mocks base method.
func (m *MockRequester[Request, Response]) Delete(ctx context.Context, path string) (Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, path)
	ret0, _ := ret[0].(Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockRequesterMockRecorder[Request, Response]) Delete(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRequester[Request, Response])(nil).Delete), ctx, path)
}

// Get mocks base method.
func (m *MockRequester[Request, Response]) Get(ctx context.Context, path string) (Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, path)
	ret0, _ := ret[0].(Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRequesterMockRecorder[Request, Response]) Get(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRequester[Request, Response])(nil).Get), ctx, path)
}

// Post mocks base method.
func (m *MockRequester[Request, Response]) Post(ctx context.Context, path string, request *Request) (Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", ctx, path, request)
	ret0, _ := ret[0].(Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Post indicates an expected call of Post.
func (mr *MockRequesterMockRecorder[Request, Response]) Post(ctx, path, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockRequester[Request, Response])(nil).Post), ctx, path, request)
}

// Put mocks base method.
func (m *MockRequester[Request, Response]) Put(ctx context.Context, path string, request *Request) (Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, path, request)
	ret0, _ := ret[0].(Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockRequesterMockRecorder[Request, Response]) Put(ctx, path, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockRequester[Request, Response])(nil).Put), ctx, path, request)
}
