// Code generated by MockGen. DO NOT EDIT.
// Source: internal/routeregistry/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/routeregistry/service.go -destination=test/mocks/mock_routeregistry/mock_registry_service.go -package=mock_routeregistry
//

// Package mock_routeregistry is a generated GoMock package.
package mock_routeregistry

import (
	context "context"
	reflect "reflect"

	routeregistry "github.com/llnl/wormhole-cli/internal/routeregistry"
	gomock "go.uber.org/mock/gomock"
)

// MockRegistryService is a mock of RegistryService interface.
type MockRegistryService struct {
	ctrl     *gomock.Controller
	recorder *MockRegistryServiceMockRecorder
	isgomock struct{}
}

// MockRegistryServiceMockRecorder is the mock recorder for MockRegistryService.
type MockRegistryServiceMockRecorder struct {
	mock *MockRegistryService
}

// NewMockRegistryService creates a new mock instance.
func NewMockRegistryService(ctrl *gomock.Controller) *MockRegistryService {
	mock := &MockRegistryService{ctrl: ctrl}
	mock.recorder = &MockRegistryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistryService) EXPECT() *MockRegistryServiceMockRecorder {
	return m.recorder
}

// AddCommunity mocks base method.
func (m *MockRegistryService) AddCommunity(ctx context.Context, name string) (*routeregistry.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCommunity", ctx, name)
	ret0, _ := ret[0].(*routeregistry.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddCommunity indicates an expected call of AddCommunity.
func (mr *MockRegistryServiceMockRecorder) AddCommunity(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCommunity", reflect.TypeOf((*MockRegistryService)(nil).AddCommunity), ctx, name)
}

// AddCommunityRoute mocks base method.
func (m *MockRegistryService) AddCommunityRoute(ctx context.Context, communityID, routeID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCommunityRoute", ctx, communityID, routeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCommunityRoute indicates an expected call of AddCommunityRoute.
func (mr *MockRegistryServiceMockRecorder) AddCommunityRoute(ctx, communityID, routeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCommunityRoute", reflect.TypeOf((*MockRegistryService)(nil).AddCommunityRoute), ctx, communityID, routeID)
}

// ListCommunities mocks base method.
func (m *MockRegistryService) ListCommunities(ctx context.Context, identifier string) ([]routeregistry.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCommunities", ctx, identifier)
	ret0, _ := ret[0].([]routeregistry.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCommunities indicates an expected call of ListCommunities.
func (mr *MockRegistryServiceMockRecorder) ListCommunities(ctx, identifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCommunities", reflect.TypeOf((*MockRegistryService)(nil).ListCommunities), ctx, identifier)
}

// ListRoutes mocks base method.
func (m *MockRegistryService) ListRoutes(ctx context.Context, identifier string) ([]routeregistry.Route, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoutes", ctx, identifier)
	ret0, _ := ret[0].([]routeregistry.Route)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoutes indicates an expected call of ListRoutes.
func (mr *MockRegistryServiceMockRecorder) ListRoutes(ctx, identifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoutes", reflect.TypeOf((*MockRegistryService)(nil).ListRoutes), ctx, identifier)
}

// RemoveCommunity mocks base method.
func (m *MockRegistryService) RemoveCommunity(ctx context.Context, identifier string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCommunity", ctx, identifier)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveCommunity indicates an expected call of RemoveCommunity.
func (mr *MockRegistryServiceMockRecorder) RemoveCommunity(ctx, identifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCommunity", reflect.TypeOf((*MockRegistryService)(nil).RemoveCommunity), ctx, identifier)
}

// RemoveCommunityRoute mocks base method.
func (m *MockRegistryService) RemoveCommunityRoute(ctx context.Context, communityID, routeID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCommunityRoute", ctx, communityID, routeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveCommunityRoute indicates an expected call of RemoveCommunityRoute.
func (mr *MockRegistryServiceMockRecorder) RemoveCommunityRoute(ctx, communityID, routeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCommunityRoute", reflect.TypeOf((*MockRegistryService)(nil).RemoveCommunityRoute), ctx, communityID, routeID)
}

// ResolveCommunity mocks base method.
func (m *MockRegistryService) ResolveCommunity(ctx context.Context, identifier string) (*routeregistry.Community, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveCommunity", ctx, identifier)
	ret0, _ := ret[0].(*routeregistry.Community)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveCommunity indicates an expected call of ResolveCommunity.
func (mr *MockRegistryServiceMockRecorder) ResolveCommunity(ctx, identifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveCommunity", reflect.TypeOf((*MockRegistryService)(nil).ResolveCommunity), ctx, identifier)
}

// ResolveRoute mocks base method.
func (m *MockRegistryService) ResolveRoute(ctx context.Context, identifier string) (*routeregistry.Route, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveRoute", ctx, identifier)
	ret0, _ := ret[0].(*routeregistry.Route)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveRoute indicates an expected call of ResolveRoute.
func (mr *MockRegistryServiceMockRecorder) ResolveRoute(ctx, identifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveRoute", reflect.TypeOf((*MockRegistryService)(nil).ResolveRoute), ctx, identifier)
}
